# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=100)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4)),
                ('untappd_url', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['beer_name'],
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beers',
            },
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='breweries')),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brewery_name'],
                'verbose_name': 'Brewery',
                'verbose_name_plural': 'Breweries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Event_Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewmaster', models.BooleanField(default=False)),
                ('bottle_row', models.BooleanField(default=False)),
                ('vip', models.BooleanField(default=False)),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbtf.Beer')),
            ],
            options={
                'verbose_name': 'Event_Beer',
                'verbose_name_plural': 'Event_Beers',
            },
        ),
        migrations.CreateModel(
            name='Event_Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('booth', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('added_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbtf.Brewery')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbtf.Event')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event_Brewery',
                'verbose_name_plural': 'Event_Breweries',
            },
        ),
        migrations.AddField(
            model_name='event_beer',
            name='event_brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbtf.Event_Brewery'),
        ),
        migrations.AddField(
            model_name='event_beer',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lbtf.Brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='event_brewery',
            unique_together=set([('event', 'brewery')]),
        ),
        migrations.AlterUniqueTogether(
            name='event_beer',
            unique_together=set([('event_brewery', 'beer')]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('event_name', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together=set([('brewery', 'beer_name')]),
        ),
    ]
