# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbtf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='beer_advocate_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='rate_beer_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='website',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(choices=[('Altbier', 'Altbier'), ('American Amber / Red Ale', 'American Amber / Red Ale'), ('American Amber / Red Lager', 'American Amber / Red Lager'), ('American Barleywine', 'American Barleywine'), ('American Blonde Ale', 'American Blonde Ale'), ('American Brown Ale', 'American Brown Ale'), ('American IPA', 'American IPA'), ('American Imperial / Double Stout', 'American Imperial / Double Stout'), ('American Light Lager', 'American Light Lager'), ('American Pale Ale', 'American Pale Ale'), ('American Pale Wheat Ale', 'American Pale Wheat Ale'), ('American Porter', 'American Porter'), ('American Stout', 'American Stout'), ('American Strong Ale', 'American Strong Ale'), ('American Wild Ale', 'American Wild Ale'), ('Applewine', 'Applewine'), ('Australian Pale Ale', 'Australian Pale Ale'), ('Australian Sparkling Ale', 'Australian Sparkling Ale'), ('Baltic Porter', 'Baltic Porter'), ('Belgian Blonde / Golden', 'Belgian Blonde / Golden'), ('Belgian Brown Ale', 'Belgian Brown Ale'), ('Belgian Dubbel', 'Belgian Dubbel'), ('Belgian IPA', 'Belgian IPA'), ('Belgian Pale Ale', 'Belgian Pale Ale'), ('Belgian Quad', 'Belgian Quad'), ('Belgian Strong Dark Ale', 'Belgian Strong Dark Ale'), ('Belgian Strong Pale Ale', 'Belgian Strong Pale Ale'), ('Belgian Tripel', 'Belgian Tripel'), ('Berliner Weisse', 'Berliner Weisse'), ('Bi\xe8re de Champagne / Bi\xe8re Brut', 'Bi\xe8re de Champagne / Bi\xe8re Brut'), ('Bi\xe8re de Garde', 'Bi\xe8re de Garde'), ('Black & Tan', 'Black & Tan'), ('Black IPA / Cascadian Dark Ale', 'Black IPA / Cascadian Dark Ale'), ('Black Lager', 'Black Lager'), ('Blonde Ale', 'Blonde Ale'), ('Blonde Lager', 'Blonde Lager'), ('Bock', 'Bock'), ('Braggot', 'Braggot'), ('Burton Ale', 'Burton Ale'), ('California Common', 'California Common'), ('Chili Beer', 'Chili Beer'), ('Cider', 'Cider'), ('Cream Ale', 'Cream Ale'), ('Cyser', 'Cyser'), ('Czech Pilsener', 'Czech Pilsener'), ('Dampfbier', 'Dampfbier'), ('Dark Ale', 'Dark Ale'), ('Doppelbock', 'Doppelbock'), ('Dortmunder / Export Lager', 'Dortmunder / Export Lager'), ('Dunkel Munich Lager', 'Dunkel Munich Lager'), ('Dunkelweizen', 'Dunkelweizen'), ('Eisbock', 'Eisbock'), ('English Barleywine', 'English Barleywine'), ('English Bitter', 'English Bitter'), ('English Brown Ale', 'English Brown Ale'), ('English IPA', 'English IPA'), ('English Mild Ale', 'English Mild Ale'), ('English Pale Ale', 'English Pale Ale'), ('English Porter', 'English Porter'), ('English Strong Ale', 'English Strong Ale'), ('Euro Dark Lager', 'Euro Dark Lager'), ('Euro Lager', 'Euro Lager'), ('Extra Special / Strong Bitter', 'Extra Special / Strong Bitter'), ('Faro', 'Faro'), ('Flanders Oud Bruin', 'Flanders Oud Bruin'), ('Flanders Red Ale', 'Flanders Red Ale'), ('Foreign / Export Stout', 'Foreign / Export Stout'), ('Fruit Beer', 'Fruit Beer'), ('German Pilsner', 'German Pilsner'), ('Ginger Beer', 'Ginger Beer'), ('Gluten-Free', 'Gluten-Free'), ('Golden Ale', 'Golden Ale'), ('Golden Lager', 'Golden Lager'), ('Gose', 'Gose'), ('Gruit / Ancient Herbed Ale', 'Gruit / Ancient Herbed Ale'), ('Gr\xe4tzer / Grodziskie', 'Gr\xe4tzer / Grodziskie'), ('Gueuze', 'Gueuze'), ('Happoshu', 'Happoshu'), ('Harvest Ale', 'Harvest Ale'), ('Hefeweizen', 'Hefeweizen'), ('Hefeweizen Light / Leicht', 'Hefeweizen Light / Leicht'), ('Helles Lager', 'Helles Lager'), ('Herbed/Spiced Beer', 'Herbed/Spiced Beer'), ('IPL (India Pale Lager)', 'IPL (India Pale Lager)'), ('Imperial / Double Black IPA', 'Imperial / Double Black IPA'), ('Imperial / Double Brown Ale', 'Imperial / Double Brown Ale'), ('Imperial / Double IPA', 'Imperial / Double IPA'), ('Imperial / Double Pilsner', 'Imperial / Double Pilsner'), ('Imperial / Double Porter', 'Imperial / Double Porter'), ('Imperial / Double Red Ale', 'Imperial / Double Red Ale'), ('Imperial / Double Stout', 'Imperial / Double Stout'), ('Imperial Oatmeal Stout', 'Imperial Oatmeal Stout'), ('Irish Dry Stout', 'Irish Dry Stout'), ('Irish Red Ale', 'Irish Red Ale'), ('Japanese Rice Lager', 'Japanese Rice Lager'), ('Kellerbier / Zwickelbier', 'Kellerbier / Zwickelbier'), ('Kombucha', 'Kombucha'), ('Kristallweizen', 'Kristallweizen'), ('Kvass', 'Kvass'), ('K\xf6lsch', 'K\xf6lsch'), ('Lambic', 'Lambic'), ('Maibock/Helles Bock', 'Maibock/Helles Bock'), ('Malt Beer', 'Malt Beer'), ('Malt Liquor', 'Malt Liquor'), ('Mead', 'Mead'), ('Melomel', 'Melomel'), ('Milk / Sweet Stout', 'Milk / Sweet Stout'), ('New Zealand Pale Ale', 'New Zealand Pale Ale'), ('Non-Alcoholic', 'Non-Alcoholic'), ('North American Adjunct Lager', 'North American Adjunct Lager'), ('Oatmeal Stout', 'Oatmeal Stout'), ('Oktoberfest/Festbier/M\xe4rzen', 'Oktoberfest/Festbier/M\xe4rzen'), ('Old Ale', 'Old Ale'), ('Oyster Stout', 'Oyster Stout'), ('Pale Lager', 'Pale Lager'), ('Patersbier', 'Patersbier'), ('Perry', 'Perry'), ('Pilsner', 'Pilsner'), ('Porter', 'Porter'), ('Pumpkin / Yam Beer', 'Pumpkin / Yam Beer'), ('Pyment', 'Pyment'), ('Radler', 'Radler'), ('Rauchbier', 'Rauchbier'), ('Roggenbier', 'Roggenbier'), ('Root Beer', 'Root Beer'), ('Russian Imperial Stout', 'Russian Imperial Stout'), ('Rye Beer', 'Rye Beer'), ('Sahti', 'Sahti'), ('Saison / Farmhouse Ale', 'Saison / Farmhouse Ale'), ('Schwarzbier', 'Schwarzbier'), ('Scotch Ale / Wee Heavy', 'Scotch Ale / Wee Heavy'), ('Scottish Ale', 'Scottish Ale'), ('Scottish Export Ale', 'Scottish Export Ale'), ('Session IPA', 'Session IPA'), ('Smoked Beer', 'Smoked Beer'), ('Sour Ale', 'Sour Ale'), ('Specialty Grain', 'Specialty Grain'), ('Stout', 'Stout'), ('Triple IPA', 'Triple IPA'), ('Vienna Lager', 'Vienna Lager'), ('Weizenbock', 'Weizenbock'), ('Wheat Wine', 'Wheat Wine'), ('White IPA', 'White IPA'), ('Winter Ale', 'Winter Ale'), ('Winter Lager', 'Winter Lager'), ('Winter Warmer', 'Winter Warmer'), ('Witbier', 'Witbier')], max_length=255),
        ),
    ]
