# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbtf', '0003_auto_20160210_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='brewery_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
