# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbtf', '0004_brewery_brewery_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
